services:
  - type: web
    name: shaeantoine.io
    env: static
    buildCommand: echo "No build required"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /about
        destination: /about.html